const books = [
    {
        id: "ishod",
        title: "Андрей Круз, Мария Круз - Земля лишних.Исход",
        cover: "img/исход.jpg",
        audioFiles: [
        { title: "Файл 1", file: "audio/Isxod/01.mp3" },
        { title: "Файл 2", file: "audio/Isxod/02.mp3" },
        { title: "Файл 3", file: "audio/Isxod/03.mp3" },
        { title: "Файл 4", file: "audio/Isxod/04.mp3" },
        { title: "Файл 5", file: "audio/Isxod/05.mp3" },
        { title: "Файл 6", file: "audio/Isxod/06.mp3" },
        { title: "Файл 7", file: "audio/Isxod/07.mp3" },
        { title: "Файл 8", file: "audio/Isxod/08.mp3" },
        { title: "Файл 9", file: "audio/Isxod/09.mp3" },
        { title: "Файл 10", file: "audio/Isxod/10.mp3" },
        { title: "Файл 11", file: "audio/Isxod/11.mp3" },
        { title: "Файл 12", file: "audio/Isxod/12.mp3" },
        { title: "Файл 13", file: "audio/Isxod/13.mp3" },
        { title: "Файл 14", file: "audio/Isxod/14.mp3" },
        { title: "Файл 15", file: "audio/Isxod/15.mp3" },
        { title: "Файл 16", file: "audio/Isxod/16.mp3" },
        { title: "Файл 17", file: "audio/Isxod/17.mp3" },
        { title: "Файл 18", file: "audio/Isxod/18.mp3" },
        { title: "Файл 19", file: "audio/Isxod/19.mp3" },
        { title: "Файл 20", file: "audio/Isxod/20.mp3" },
        { title: "Файл 21", file: "audio/Isxod/21.mp3" },
        { title: "Файл 22", file: "audio/Isxod/22.mp3" },
        { title: "Файл 23", file: "audio/Isxod/23.mp3" },
        { title: "Файл 24", file: "audio/Isxod/24.mp3" },
        { title: "Файл 25", file: "audio/Isxod/25.mp3" }
        ]
    },
    {
    id: "novaja",
    title: "Андрей Круз, Мария Круз - Земля лишних.Новая жизнь",
    cover: "img/новая жизнь.jpg",
    audioFiles: [
        { title: "Файл 1", file: "audio/novaja/02_01.mp3" },
        { title: "Файл 2", file: "audio/novaja/02_02.mp3" },
        { title: "Файл 3", file: "audio/novaja/02_03.mp3" },
        { title: "Файл 4", file: "audio/novaja/02_04.mp3" },
        { title: "Файл 5", file: "audio/novaja/02_05.mp3" },
        { title: "Файл 6", file: "audio/novaja/02_06.mp3" },
        { title: "Файл 7", file: "audio/novaja/02_07.mp3" },
        { title: "Файл 8", file: "audio/novaja/02_08.mp3" },
        { title: "Файл 9", file: "audio/novaja/02_09.mp3" },
        { title: "Файл 10", file: "audio/novaja/02_10.mp3" },
        { title: "Файл 11", file: "audio/novaja/02_11.mp3" },
        { title: "Файл 12", file: "audio/novaja/02_12.mp3" },
        { title: "Файл 13", file: "audio/novaja/02_13.mp3" },
        { title: "Файл 14", file: "audio/novaja/02_14.mp3" },
        { title: "Файл 15", file: "audio/novaja/02_15.mp3" },
        { title: "Файл 16", file: "audio/novaja/02_16.mp3" },
        { title: "Файл 17", file: "audio/novaja/02_17.mp3" },
        { title: "Файл 18", file: "audio/novaja/02_18.mp3" },
        { title: "Файл 19", file: "audio/novaja/02_19.mp3" },
        { title: "Файл 20", file: "audio/novaja/02_20.mp3" },
        { title: "Файл 21", file: "audio/novaja/02_21.mp3" },
        { title: "Файл 22", file: "audio/novaja/02_22.mp3" },
        { title: "Файл 23", file: "audio/novaja/02_23.mp3" },
        { title: "Файл 24", file: "audio/novaja/02_24.mp3" },
        { title: "Файл 25", file: "audio/novaja/02_25.mp3" }
        ]
    },
    {
    id: "za_drugi_svoya",
    title: "Андрей Круз, Мария Круз - Земля лишних.За други своя",
    cover: "img/за дурги своя.jpg",
    audioFiles: [
        { title: "Файл 1", file: "audio/za%20drugi%20svoya/m01.mp3" },
        { title: "Файл 2", file: "audio/za%20drugi%20svoya/m02.mp3" },
        { title: "Файл 3", file: "audio/za%20drugi%20svoya/m03.mp3" },
        { title: "Файл 4", file: "audio/za%20drugi%20svoya/m04.mp3" },
        { title: "Файл 5", file: "audio/za%20drugi%20svoya/m05.mp3" },
        { title: "Файл 6", file: "audio/za%20drugi%20svoya/m06.mp3" },
        { title: "Файл 7", file: "audio/za%20drugi%20svoya/m07.mp3" },
        { title: "Файл 8", file: "audio/za%20drugi%20svoya/m08.mp3" },
        { title: "Файл 9", file: "audio/za%20drugi%20svoya/m09.mp3" },
        { title: "Файл 10", file: "audio/za%20drugi%20svoya/m10.mp3" },
        { title: "Файл 11", file: "audio/za%20drugi%20svoya/m11.mp3" },
        { title: "Файл 12", file: "audio/za%20drugi%20svoya/m12.mp3" },
        { title: "Файл 13", file: "audio/za%20drugi%20svoya/m13.mp3" },
        { title: "Файл 14", file: "audio/za%20drugi%20svoya/m14.mp3" },
        { title: "Файл 15", file: "audio/za%20drugi%20svoya/m15.mp3" },
        { title: "Файл 16", file: "audio/za%20drugi%20svoya/m16.mp3" },
        { title: "Файл 17", file: "audio/za%20drugi%20svoya/m17.mp3" },
        { title: "Файл 18", file: "audio/za%20drugi%20svoya/m18.mp3" }
        ]
    },
    {
    id: "pohod",
    title: "Андрей Круз - У Великой реки.Поход",
    cover: "img/pohod.png",
    audioFiles: [
        { title: "Файл 1", file: "audio/Pohod/001.mp3" },
        { title: "Файл 2", file: "audio/Pohod/002.mp3" },
        { title: "Файл 3", file: "audio/Pohod/003.mp3" },
        { title: "Файл 4", file: "audio/Pohod/004.mp3" },
        { title: "Файл 5", file: "audio/Pohod/005.mp3" },
        { title: "Файл 6", file: "audio/Pohod/006.mp3" },
        { title: "Файл 7", file: "audio/Pohod/007.mp3" },
        { title: "Файл 8", file: "audio/Pohod/008.mp3" },
        { title: "Файл 9", file: "audio/Pohod/009.mp3" },
        { title: "Файл 10", file: "audio/Pohod/010.mp3" },
        { title: "Файл 11", file: "audio/Pohod/011.mp3" },
        { title: "Файл 12", file: "audio/Pohod/012.mp3" },
        { title: "Файл 13", file: "audio/Pohod/013.mp3" },
        { title: "Файл 14", file: "audio/Pohod/014.mp3" },
        { title: "Файл 15", file: "audio/Pohod/015.mp3" },
        { title: "Файл 16", file: "audio/Pohod/016.mp3" },
        { title: "Файл 17", file: "audio/Pohod/017.mp3" },
        { title: "Файл 18", file: "audio/Pohod/018.mp3" },
        { title: "Файл 19", file: "audio/Pohod/019.mp3" },
        { title: "Файл 20", file: "audio/Pohod/020.mp3" },
        { title: "Файл 21", file: "audio/Pohod/021.mp3" },
        { title: "Файл 22", file: "audio/Pohod/022.mp3" },
        { title: "Файл 23", file: "audio/Pohod/023.mp3" },
        { title: "Файл 24", file: "audio/Pohod/024.mp3" },
        { title: "Файл 25", file: "audio/Pohod/025.mp3" },
        { title: "Файл 26", file: "audio/Pohod/026.mp3" },
        { title: "Файл 27", file: "audio/Pohod/027.mp3" },
        { title: "Файл 28", file: "audio/Pohod/028.mp3" },
        { title: "Файл 29", file: "audio/Pohod/029.mp3" },
        { title: "Файл 30", file: "audio/Pohod/030.mp3" },
        { title: "Файл 31", file: "audio/Pohod/031.mp3" },
        { title: "Файл 32", file: "audio/Pohod/032.mp3" },
        { title: "Файл 33", file: "audio/Pohod/033.mp3" },
        { title: "Файл 34", file: "audio/Pohod/034.mp3" },
        { title: "Файл 35", file: "audio/Pohod/035.mp3" },
        { title: "Файл 36", file: "audio/Pohod/036.mp3" },
        { title: "Файл 37", file: "audio/Pohod/037.mp3" },
        { title: "Файл 38", file: "audio/Pohod/038.mp3" },
        { title: "Файл 39", file: "audio/Pohod/039.mp3" },
        { title: "Файл 40", file: "audio/Pohod/040.mp3" }
        ]
    },
    {
    id: "bitwa",
    title: "Андрей Круз - У Великой реки.Битва",
    cover: "img/bitwa.png",
    audioFiles: [
        { title: "Файл 1", file: "audio/Bitwa/001.mp3" },
        { title: "Файл 2", file: "audio/Bitwa/002.mp3" },
        { title: "Файл 3", file: "audio/Bitwa/003.mp3" },
        { title: "Файл 4", file: "audio/Bitwa/004.mp3" },
        { title: "Файл 5", file: "audio/Bitwa/005.mp3" },
        { title: "Файл 6", file: "audio/Bitwa/006.mp3" },
        { title: "Файл 7", file: "audio/Bitwa/007.mp3" },
        { title: "Файл 8", file: "audio/Bitwa/008.mp3" },
        { title: "Файл 9", file: "audio/Bitwa/009.mp3" },
        { title: "Файл 10", file: "audio/Bitwa/010.mp3" },
        { title: "Файл 11", file: "audio/Bitwa/011.mp3" },
        { title: "Файл 12", file: "audio/Bitwa/012.mp3" },
        { title: "Файл 13", file: "audio/Bitwa/013.mp3" },
        { title: "Файл 14", file: "audio/Bitwa/014.mp3" },
        { title: "Файл 15", file: "audio/Bitwa/015.mp3" },
        { title: "Файл 16", file: "audio/Bitwa/016.mp3" },
        { title: "Файл 17", file: "audio/Bitwa/017.mp3" },
        { title: "Файл 18", file: "audio/Bitwa/018.mp3" },
        { title: "Файл 19", file: "audio/Bitwa/019.mp3" },
        { title: "Файл 20", file: "audio/Bitwa/020.mp3" },
        { title: "Файл 21", file: "audio/Bitwa/021.mp3" },
        { title: "Файл 22", file: "audio/Bitwa/022.mp3" }
        ]
    }
];