const books = [
    {
        id: "ishod",
        title: "Андрей Круз, Мария Круз - Земля лишних.Исход",
        cover: "img/исход.jpg",
        audioFiles: [
        { title: "Глава 1", file: "audio/Isxod/01.mp3" },
        { title: "Глава 2", file: "audio/Isxod/02.mp3" },
        { title: "Глава 3", file: "audio/Isxod/03.mp3" },
        { title: "Глава 4", file: "audio/Isxod/04.mp3" },
        { title: "Глава 5", file: "audio/Isxod/05.mp3" },
        { title: "Глава 6", file: "audio/Isxod/06.mp3" },
        { title: "Глава 7", file: "audio/Isxod/07.mp3" },
        { title: "Глава 8", file: "audio/Isxod/08.mp3" },
        { title: "Глава 9", file: "audio/Isxod/09.mp3" },
        { title: "Глава 10", file: "audio/Isxod/10.mp3" },
        { title: "Глава 11", file: "audio/Isxod/11.mp3" },
        { title: "Глава 12", file: "audio/Isxod/12.mp3" },
        { title: "Глава 13", file: "audio/Isxod/13.mp3" },
        { title: "Глава 14", file: "audio/Isxod/14.mp3" },
        { title: "Глава 15", file: "audio/Isxod/15.mp3" },
        { title: "Глава 16", file: "audio/Isxod/16.mp3" },
        { title: "Глава 17", file: "audio/Isxod/17.mp3" },
        { title: "Глава 18", file: "audio/Isxod/18.mp3" },
        { title: "Глава 19", file: "audio/Isxod/19.mp3" },
        { title: "Глава 20", file: "audio/Isxod/20.mp3" },
        { title: "Глава 21", file: "audio/Isxod/21.mp3" },
        { title: "Глава 22", file: "audio/Isxod/22.mp3" },
        { title: "Глава 23", file: "audio/Isxod/23.mp3" },
        { title: "Глава 24", file: "audio/Isxod/24.mp3" },
        { title: "Глава 25", file: "audio/Isxod/25.mp3" }
        ]
    },
    {
    id: "novaja",
    title: "Андрей Круз, Мария Круз - Земля лишних.Новая жизнь",
    cover: "img/новая жизнь.jpg",
    audioFiles: [
        { title: "Глава 1", file: "audio/novaja/02_01.mp3" },
        { title: "Глава 2", file: "audio/novaja/02_02.mp3" },
        { title: "Глава 3", file: "audio/novaja/02_03.mp3" },
        { title: "Глава 4", file: "audio/novaja/02_04.mp3" },
        { title: "Глава 5", file: "audio/novaja/02_05.mp3" },
        { title: "Глава 6", file: "audio/novaja/02_06.mp3" },
        { title: "Глава 7", file: "audio/novaja/02_07.mp3" },
        { title: "Глава 8", file: "audio/novaja/02_08.mp3" },
        { title: "Глава 9", file: "audio/novaja/02_09.mp3" },
        { title: "Глава 10", file: "audio/novaja/02_10.mp3" },
        { title: "Глава 11", file: "audio/novaja/02_11.mp3" },
        { title: "Глава 12", file: "audio/novaja/02_12.mp3" },
        { title: "Глава 13", file: "audio/novaja/02_13.mp3" },
        { title: "Глава 14", file: "audio/novaja/02_14.mp3" },
        { title: "Глава 15", file: "audio/novaja/02_15.mp3" },
        { title: "Глава 16", file: "audio/novaja/02_16.mp3" },
        { title: "Глава 17", file: "audio/novaja/02_17.mp3" },
        { title: "Глава 18", file: "audio/novaja/02_18.mp3" },
        { title: "Глава 19", file: "audio/novaja/02_19.mp3" },
        { title: "Глава 20", file: "audio/novaja/02_20.mp3" },
        { title: "Глава 21", file: "audio/novaja/02_21.mp3" },
        { title: "Глава 22", file: "audio/novaja/02_22.mp3" },
        { title: "Глава 23", file: "audio/novaja/02_23.mp3" },
        { title: "Глава 24", file: "audio/novaja/02_24.mp3" },
        { title: "Глава 25", file: "audio/novaja/02_25.mp3" }
        ]
    },
    {
    id: "za_drugi_svoya",
    title: "Андрей Круз, Мария Круз - Земля лишних.За други своя",
    cover: "img/за дурги своя.jpg",
    audioFiles: [
        { title: "Глава 1", file: "audio/za%20drugi%20svoya/m01.mp3" },
        { title: "Глава 2", file: "audio/za%20drugi%20svoya/m02.mp3" },
        { title: "Глава 3", file: "audio/za%20drugi%20svoya/m03.mp3" },
        { title: "Глава 4", file: "audio/za%20drugi%20svoya/m04.mp3" },
        { title: "Глава 5", file: "audio/za%20drugi%20svoya/m05.mp3" },
        { title: "Глава 6", file: "audio/za%20drugi%20svoya/m06.mp3" },
        { title: "Глава 7", file: "audio/za%20drugi%20svoya/m07.mp3" },
        { title: "Глава 8", file: "audio/za%20drugi%20svoya/m08.mp3" },
        { title: "Глава 9", file: "audio/za%20drugi%20svoya/m09.mp3" },
        { title: "Глава 10", file: "audio/za%20drugi%20svoya/m10.mp3" },
        { title: "Глава 11", file: "audio/za%20drugi%20svoya/m11.mp3" },
        { title: "Глава 12", file: "audio/za%20drugi%20svoya/m12.mp3" },
        { title: "Глава 13", file: "audio/za%20drugi%20svoya/m13.mp3" },
        { title: "Глава 14", file: "audio/za%20drugi%20svoya/m14.mp3" },
        { title: "Глава 15", file: "audio/za%20drugi%20svoya/m15.mp3" },
        { title: "Глава 16", file: "audio/za%20drugi%20svoya/m16.mp3" },
        { title: "Глава 17", file: "audio/za%20drugi%20svoya/m17.mp3" },
        { title: "Глава 18", file: "audio/za%20drugi%20svoya/m18.mp3" }
        ]
    }
];
